---
  title: "ProfessionalHires"
output: html_document
---
  
  ### Install Necessary Libraries
  
  ```{r}
library(dplyr) 
library(ggplot2) 
```

### Store csv file as a data frame

```{r}
profhires.df <- read.csv('data/ProfessionalHires.csv')
profhires.df 
```

## Prep Data for analysis
```{r}

# organize and clean data frame
  profhires.df <- profhires.df %>% 
    arrange(Year)

  colnames(profhires.df)[colnames(profhires.df )=="Year"] <- "AcademicYear"

  # Categorize Academic Year by beginnning year (for graphing purposes)
  profhires.df <- profhires.df %>%
    mutate(Year = substr(AcademicYear, 0, 4))
  
  # Change types to numeric (for graphing purposes)
  profhires.df$Count <- as.numeric(profhires.df$Count)
  profhires.df$Year <- as.numeric(profhires.df$Year)

#Create necessary calculated columns
  
  # Calculate total number of new hires for each year
  total.df <- aggregate(. ~ Year, data=profhires.df, FUN=sum) 
  
  # Merge tables
  merged.df <- merge(profhires.df, total.df, by="Year")
  merged.df$Percentage <- merged.df$Count.x / merged.df$Count.y
  
  # Add Percentage Column
  profhires.df$Percentage <- merged.df$Percentage
  
  # Add Percentage Change between Counts
  profhires.df  <- profhires.df %>% 
    arrange(College) %>% 
    group_by(College)  %>% 
    mutate(count.pChange = ((Count - lag(Count)) / lag(Count)))
  
  # Add Percentage Change between Percentages
  profhires.df  <- profhires.df %>% 
    arrange(College) %>% 
    group_by(College)  %>% 
    mutate(percent.pChange = (Percentage-lag(Percentage)))
  
  # Remove
  profhires.df 
  
### Split by Campus

  #Extract Tacoma and Bothell
  UWTacoma <- profhires.df %>% 
    filter(College == "UW Tacoma")
  UWTacoma
  
  UWBothell <- profhires.df %>% 
    filter(College == "UW Bothell")
  UWBothell
  
  # Consolidate UW Seattle data
  UWSeattle <- total.df
  UWSeattle$College <- "UW Seattle"
  UWSeattle$College = as.factor(UWSeattle$College)
  UWSeattle$Count <- UWSeattle$Count - UWTacoma$Count - UWBothell$Count
  
    # Add Percentage Column
    UWSeattle$Percentage <- UWSeattle$Count / total.df$Count
    
    # Add Percentage Change between Counts
    UWSeattle <- UWSeattle %>% 
      arrange(College) %>% 
      group_by(College)  %>% 
      mutate(count.pChange = ((Count - lag(Count)) / lag(Count)))
    
    # Add Percentage Change between Percentages
    UWSeattle <- UWSeattle %>% 
      arrange(College) %>% 
      group_by(College)  %>% 
      mutate(percent.pChange = (Percentage-lag(Percentage)))
    UWSeattle
  
  AllCampus <- union(UWBothell, UWTacoma)
  AllCampus <- union(AllCampus, UWSeattle)

```

## Trend Analysis

### Plot Counts
```{r}
# Overall Counts

# scatterplot
overallPlot <- ggplot(data = total.df, aes(x = Year, y = Count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) # LINES ARE NOT SHOWING UP ON GRAPH?? :(
overallPlot

# bar graph
overallBar <- ggplot(data = total.df, aes(x = Year, y = Count)) +
  geom_bar(stat="identity")
overallBar

## Plot counts for each College 

basicPlotC <- ggplot(data = profhires.df, aes(x = Year, y = Count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) # LINES ARE NOT SHOWING UP ON GRAPH?? :(
# geom_smooth(method = "lm", se = FALSE) # lines are vertical
basicPlotC

# scatter plot - Colleges separate by color
colorPlotC <- ggplot(data = profhires.df, aes(x = Year, y = Count, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
#geom_smooth(method = "lm", se = FALSE) # NOT SHOWING UP EITHER
colorPlotC

# scatter plot - Colleges separate by facets
facetPlotC <- basicPlotC + facet_wrap( ~ College, ncol=3)
facetPlotC

# bar graph - College sepeated by stacked bars
stackedBarC <- ggplot(data = profhires.df, aes(x = Year, y = Count, fill = College )) +
  geom_bar(stat="identity")
stackedBarC

# bar graph- Colleges separate by facets
facetGraphC <- stackedBarC+ facet_wrap( ~ College, ncol=3)
facetGraphC

```


### Plot Percentages
```{r}
## Plot percentages for each College 

basicPlotP <- ggplot(data = profhires.df, aes(x = Year, y = Percentage)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) # LINES ARE NOT SHOWING UP ON GRAPH?? :(
basicPlotP

# scatter plot - Colleges separate by color
colorPlotP <- ggplot(data = profhires.df, aes(x = Year, y = Percentage, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
colorPlotP

# scatter plot - Colleges separate by facets
facetPlotP <- basicPlotP + facet_wrap( ~ College, ncol=3)
facetPlotP

# bar graph - College sepeated by stacked bars
stackedBarP <- ggplot(data = profhires.df, aes(x = Year, y = Percentage, fill = College )) +
  geom_bar(stat="identity")
stackedBarP

# bar graph- Colleges separate by facets
facetGraphP <- stackedBarP + facet_wrap( ~ College, ncol=3)
facetGraphP

# idk what's the best way to display the data from the above options ^^^^^^^
```


### Plot Count Changes
```{r}
# Plot percent changes of counts for each college

basicPlotPC <- ggplot(data = profhires.df, aes(x = Year, y = count.pChange)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) # LINES ARE NOT SHOWING UP ON GRAPH?? :(
basicPlotPC

# scatter plot - Colleges separate by color
colorPlotPC <- ggplot(data = profhires.df, aes(x = Year, y = count.pChange, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
colorPlotPC

# scatter plot - Colleges separate by facets
facetPlotPC <- basicPlotPC + facet_wrap( ~ College, ncol=3)
facetPlotPC

# idk what's the best way to display the data from the above options ^^^^^^^
```


### Plot Percent Changes
```{r}
# Plot percent changes of percentage for each college

basicPlotPC <- ggplot(data = profhires.df, aes(x = Year, y = percent.pChange)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
basicPlotPC

# scatter plot - Colleges separate by color
colorPlotPC <- ggplot(data = profhires.df, aes(x = Year, y = percent.pChange, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
colorPlotPC

# scatter plot - Colleges separate by facets
facetPlotPC <- basicPlot + facet_wrap( ~ College, ncol=3)
facetPlotPC

# idk what's the best way to display the data from the above options ^^^^^^^
```


## Aditional Analysis

### iSchool
```{r}

iSchool.df <- profhires.df %>% 
  filter(College == "Information School")

iSchool.df <-  iSchool.df  %>% 
  group_by(College)  %>% 
  arrange(Year)   %>% 
  mutate(count.pChange = ((Count - lag(Count)) / lag(Count) * 100))
iSchool.df 

# Plot counts
campusPlotC <- ggplot(data = iSchool.df, aes(x = Year, y = Count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotC

# Plot percentage
campusPlotP <- ggplot(data = iSchool.df, aes(x = Year, y = Percentage)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotP

# Plot count percentage change
campusPlotCP <- ggplot(data = iSchool.df, aes(x = Year, y = count.pChange)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotCP

# Plot percentage percentage change
campusPlotPP <- ggplot(data = iSchool.df, aes(x = Year, y = percent.pChange)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotPP

```

### Separated by Campus (Seattle, Tacoma, Bothell)
```{r}

# Plot counts
campusPlotC <- ggplot(data = AllCampus, aes(x = Year, y = Count, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotC

# Plot percentage
campusPlotP <- ggplot(data = AllCampus, aes(x = Year, y = Percentage, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotP

# Plot count percentage change
campusPlotCP <- ggplot(data = AllCampus, aes(x = Year, y = count.pChange, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotCP

# Plot percentage percentage change
campusPlotPP <- ggplot(data = AllCampus, aes(x = Year, y = percent.pChange, color = College)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)  # LINES ARE NOT SHOWING UP ON GRAPH?? :(
campusPlotPP
```